// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from AccessibilityManager.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class AccessibilityError : int {
    /** Some connection related error has happened when reading or writing data to the transport */
    CONNECTION_ERROR,
    /** Error due to invalid input */
    VALIDATION_ERROR,
    /** unknown general error */
    UNKNOWN_ERROR,
};

constexpr std::string_view toString(const AccessibilityError& arg) {
    switch(arg) {
        case AccessibilityError::CONNECTION_ERROR: return "CONNECTION_ERROR";
        case AccessibilityError::VALIDATION_ERROR: return "VALIDATION_ERROR";
        case AccessibilityError::UNKNOWN_ERROR: return "UNKNOWN_ERROR";
        default: return "AccessibilityError enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::AccessibilityError> {
    size_t operator()(::verifone_sdk::AccessibilityError type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
