// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_host_adapter.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class AccountType : int {
    /** Default Account to be used */
    DEFAULT,
    /** Check Account to be used */
    CHEQUE,
    /** Savings Account to be used */
    SAVINGS,
    /** Credit Account to be used */
    CREDIT,
    /** Universal Account to be used */
    UNIVERSAL,
    /** Ebt Food Account to be used */
    EBT_FOOD,
    /** Ebt Cash Account to be used */
    EBT_CASH,
    /** Stored Value to be used */
    STORED_VALUE,
    /** Debit Account to be used */
    DEBIT,
    /** Default Account to be used */
    MAX_COUNT,
};

constexpr std::string_view toString(const AccountType& arg) {
    switch(arg) {
        case AccountType::DEFAULT: return "DEFAULT";
        case AccountType::CHEQUE: return "CHEQUE";
        case AccountType::SAVINGS: return "SAVINGS";
        case AccountType::CREDIT: return "CREDIT";
        case AccountType::UNIVERSAL: return "UNIVERSAL";
        case AccountType::EBT_FOOD: return "EBT_FOOD";
        case AccountType::EBT_CASH: return "EBT_CASH";
        case AccountType::STORED_VALUE: return "STORED_VALUE";
        case AccountType::DEBIT: return "DEBIT";
        case AccountType::MAX_COUNT: return "MAX_COUNT";
        default: return "AccountType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::AccountType> {
    size_t operator()(::verifone_sdk::AccountType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
