// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from AlternativePaymentMethod.djinni

#pragma once

#include <optional>
#include <psdk/export.h>
#include <string>
#include <utility>

namespace verifone_sdk {

struct AlternativePaymentMethod; // Requiring extended class

/** Represents an alternative payment method. */
struct PSDK_EXPORT AlternativePaymentMethodBase {
    /** The id of the alternative payment method. */
    std::optional<std::string> apmId;
    /** The name of the alternative payment method. */
    std::optional<std::string> displayName;

    AlternativePaymentMethodBase(std::optional<std::string> apmId_,
                                 std::optional<std::string> displayName_)
    : apmId(std::move(apmId_))
    , displayName(std::move(displayName_))
    {}

    virtual ~AlternativePaymentMethodBase() = default;

protected:
    AlternativePaymentMethodBase(const AlternativePaymentMethodBase&) = default;
    AlternativePaymentMethodBase(AlternativePaymentMethodBase&&) = default;
    AlternativePaymentMethodBase& operator=(const AlternativePaymentMethodBase&) = default;
    AlternativePaymentMethodBase& operator=(AlternativePaymentMethodBase&&) = default;
};

}  // namespace verifone_sdk
