// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Payment.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class AuthorizationResult : int {
    /** The payment was approved */
    AUTHORIZED,
    /** The payment was rejected */
    DECLINED,
    /** The user cancelled the payment */
    USER_CANCELLED,
    /** The payment was cancelled externally */
    CANCELLED_EXTERNALLY,
    /**
     * The payment was approved using a manual, external method,
     * such as approving over the phone.
     */
    AUTHORIZED_EXTERNALLY,
    /** Used when paid by cash */
    CASH_VERIFIED,
    /**
     * This represents a payment that was voided. Use {@link #getReferencePaymentId()} to get the
     * original payment ID.
     */
    VOIDED,
    /** The reference payment could not be voided. */
    VOID_DECLINED,
    /**
     * This represents a payment that was refunded. Use {@link #getReferencePaymentId()} to get
     * the original payment ID.
     */
    REFUNDED,
    /** The reference payment could not be refunded. */
    REFUND_DECLINED,
    /** For some payment types, the final status will need to be obtained at a later time */
    IN_PROGRESS,
    /** The payment got rejected and a merchant action is required. */
    MERCHANT_ACTION_REQUIRED,
    /** Payment doesn't go through because of terminal error. */
    DEVICE_CANCELLED,
    /** Payment doesn't go through if the host is not responding to the terminal on time. */
    HOST_RESPONSE_TIMEOUT,
};

constexpr std::string_view toString(const AuthorizationResult& arg) {
    switch(arg) {
        case AuthorizationResult::AUTHORIZED: return "AUTHORIZED";
        case AuthorizationResult::DECLINED: return "DECLINED";
        case AuthorizationResult::USER_CANCELLED: return "USER_CANCELLED";
        case AuthorizationResult::CANCELLED_EXTERNALLY: return "CANCELLED_EXTERNALLY";
        case AuthorizationResult::AUTHORIZED_EXTERNALLY: return "AUTHORIZED_EXTERNALLY";
        case AuthorizationResult::CASH_VERIFIED: return "CASH_VERIFIED";
        case AuthorizationResult::VOIDED: return "VOIDED";
        case AuthorizationResult::VOID_DECLINED: return "VOID_DECLINED";
        case AuthorizationResult::REFUNDED: return "REFUNDED";
        case AuthorizationResult::REFUND_DECLINED: return "REFUND_DECLINED";
        case AuthorizationResult::IN_PROGRESS: return "IN_PROGRESS";
        case AuthorizationResult::MERCHANT_ACTION_REQUIRED: return "MERCHANT_ACTION_REQUIRED";
        case AuthorizationResult::DEVICE_CANCELLED: return "DEVICE_CANCELLED";
        case AuthorizationResult::HOST_RESPONSE_TIMEOUT: return "HOST_RESPONSE_TIMEOUT";
        default: return "AuthorizationResult enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::AuthorizationResult> {
    size_t operator()(::verifone_sdk::AuthorizationResult type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
