// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Payment.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class AuthorizationMethod : int {
    /** The user entered their pin */
    PIN,
    /** The user signed, either digitally or physically */
    SIGNATURE,
    /** The user entered their pin and signed, either digitally or physically */
    PIN_SIGNATURE,
    /** The user was required to present their ID */
    ID,
    /** The user used some other method not explicitly supported */
    OTHER,
    /** The user was not required to perform any additional action */
    NONE,
};

constexpr std::string_view toString(const AuthorizationMethod& arg) {
    switch(arg) {
        case AuthorizationMethod::PIN: return "PIN";
        case AuthorizationMethod::SIGNATURE: return "SIGNATURE";
        case AuthorizationMethod::PIN_SIGNATURE: return "PIN_SIGNATURE";
        case AuthorizationMethod::ID: return "ID";
        case AuthorizationMethod::OTHER: return "OTHER";
        case AuthorizationMethod::NONE: return "NONE";
        default: return "AuthorizationMethod enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::AuthorizationMethod> {
    size_t operator()(::verifone_sdk::AuthorizationMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
