// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Status.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class BluetoothSetupStatus : int {
    /** Successfully completed Bluetooth setup. */
    SUCCESS,
    /** Bluetooth was not enabled on the device. */
    BT_NOT_ENABLED,
    /** Bluetooth privacy settings are not setup. */
    BT_AUTH_NOT_ENABLED,
    /** Failed scanning the network for ip addresses/. */
    NETWORK_SCAN_FAILED,
    /** The previously saved device is not currently connected. */
    SAVED_DEVICE_NOT_CONNECTED,
    /** Personal hotspot is not enabled */
    TETHERING_NOT_ENABLED,
    /** Failed to select a Bluetooth device for pairing. */
    FAILED_TO_PAIR_DEVICE,
    /** Failed to save ip address for Bluetooth device. */
    FAILED_TO_SAVE_ADDRESS,
    /** Saved device device is missing a address or other information. */
    SAVED_DEVICE_MISSING_INFO,
};

constexpr std::string_view toString(const BluetoothSetupStatus& arg) {
    switch(arg) {
        case BluetoothSetupStatus::SUCCESS: return "SUCCESS";
        case BluetoothSetupStatus::BT_NOT_ENABLED: return "BT_NOT_ENABLED";
        case BluetoothSetupStatus::BT_AUTH_NOT_ENABLED: return "BT_AUTH_NOT_ENABLED";
        case BluetoothSetupStatus::NETWORK_SCAN_FAILED: return "NETWORK_SCAN_FAILED";
        case BluetoothSetupStatus::SAVED_DEVICE_NOT_CONNECTED: return "SAVED_DEVICE_NOT_CONNECTED";
        case BluetoothSetupStatus::TETHERING_NOT_ENABLED: return "TETHERING_NOT_ENABLED";
        case BluetoothSetupStatus::FAILED_TO_PAIR_DEVICE: return "FAILED_TO_PAIR_DEVICE";
        case BluetoothSetupStatus::FAILED_TO_SAVE_ADDRESS: return "FAILED_TO_SAVE_ADDRESS";
        case BluetoothSetupStatus::SAVED_DEVICE_MISSING_INFO: return "SAVED_DEVICE_MISSING_INFO";
        default: return "BluetoothSetupStatus enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::BluetoothSetupStatus> {
    size_t operator()(::verifone_sdk::BluetoothSetupStatus type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
