// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_payment.djinni

#pragma once

#include "EncryptedData.hpp"
#include <optional>
#include <psdk/export.h>
#include <string>
#include <utility>

namespace verifone_sdk {

/** Encrypted PIN and related information */
struct PSDK_EXPORT CardholderPin final {
    /** Encrypted pinblock */
    EncryptedData encPinBlock;
    /** Format of the PIN before encryption */
    std::string pinFormat;
    /** Additional information required to verify the PIN like part of the PAN, or driver ID */
    std::optional<std::string> additionalInput;

    CardholderPin(EncryptedData encPinBlock_,
                  std::string pinFormat_,
                  std::optional<std::string> additionalInput_)
    : encPinBlock(std::move(encPinBlock_))
    , pinFormat(std::move(pinFormat_))
    , additionalInput(std::move(additionalInput_))
    {}
};

}  // namespace verifone_sdk
