// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_host_adapter.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class CardEncryptionType : int {
    /** VCL encryption used for card details */
    VCL,
    /** ADE encryption used for card details */
    ADE,
    /** PKI encryption used for card details */
    PKI,
    MAX_COUNT,
};

constexpr std::string_view toString(const CardEncryptionType& arg) {
    switch(arg) {
        case CardEncryptionType::VCL: return "VCL";
        case CardEncryptionType::ADE: return "ADE";
        case CardEncryptionType::PKI: return "PKI";
        case CardEncryptionType::MAX_COUNT: return "MAX_COUNT";
        default: return "CardEncryptionType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::CardEncryptionType> {
    size_t operator()(::verifone_sdk::CardEncryptionType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
