// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from transport.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class ConnectionStatusInternal : unsigned {
    /** Default */
    UNAVAILABLE = 0,
    AVAILABLE = 1 << 0,
    DISCONNECTED = 1 << 1,
    CONNECTING = 1 << 2,
    CONNECTED = 1 << 3,
    DISCONNECTING = 1 << 4,
    /**
     * A general error, which can't be handled by some other status/mechanism.
     * This might be due to reads/writes failing for an unknown reason, or other cases.
     */
    ERROR = 1 << 5,
};
constexpr ConnectionStatusInternal operator|(ConnectionStatusInternal lhs, ConnectionStatusInternal rhs) noexcept {
    return static_cast<ConnectionStatusInternal>(static_cast<unsigned>(lhs) | static_cast<unsigned>(rhs));
}
inline ConnectionStatusInternal& operator|=(ConnectionStatusInternal& lhs, ConnectionStatusInternal rhs) noexcept {
    return lhs = lhs | rhs;
}
constexpr ConnectionStatusInternal operator&(ConnectionStatusInternal lhs, ConnectionStatusInternal rhs) noexcept {
    return static_cast<ConnectionStatusInternal>(static_cast<unsigned>(lhs) & static_cast<unsigned>(rhs));
}
inline ConnectionStatusInternal& operator&=(ConnectionStatusInternal& lhs, ConnectionStatusInternal rhs) noexcept {
    return lhs = lhs & rhs;
}
constexpr ConnectionStatusInternal operator^(ConnectionStatusInternal lhs, ConnectionStatusInternal rhs) noexcept {
    return static_cast<ConnectionStatusInternal>(static_cast<unsigned>(lhs) ^ static_cast<unsigned>(rhs));
}
inline ConnectionStatusInternal& operator^=(ConnectionStatusInternal& lhs, ConnectionStatusInternal rhs) noexcept {
    return lhs = lhs ^ rhs;
}
constexpr ConnectionStatusInternal operator~(ConnectionStatusInternal x) noexcept {
    return static_cast<ConnectionStatusInternal>(~static_cast<unsigned>(x));
}

constexpr std::string_view toString(const ConnectionStatusInternal& arg) {
    switch(arg) {
        case ConnectionStatusInternal::AVAILABLE: return "AVAILABLE";
        case ConnectionStatusInternal::DISCONNECTED: return "DISCONNECTED";
        case ConnectionStatusInternal::CONNECTING: return "CONNECTING";
        case ConnectionStatusInternal::CONNECTED: return "CONNECTED";
        case ConnectionStatusInternal::DISCONNECTING: return "DISCONNECTING";
        case ConnectionStatusInternal::ERROR: return "ERROR";
        default: return "ConnectionStatusInternal enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::ConnectionStatusInternal> {
    size_t operator()(::verifone_sdk::ConnectionStatusInternal type) const {
        return std::hash<unsigned>()(static_cast<unsigned>(type));
    }
};

}  // namespace std
