// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Decimal.djinni

#pragma once

#include <cstdint>
#include <psdk/export.h>
#include <utility>

namespace verifone_sdk {

struct Decimal; // Requiring extended class

/**
 * The Decimal class provides operations on numbers for arithmetic, scale
 * handling, rounding, comparison, and format conversion (eg. to string),
 * while retaining precision across platforms so that it can be used for currency
 */
struct PSDK_EXPORT DecimalBase {

    /** The default precision or number of digits to the right of the decimal separator. */
    static constexpr int32_t DEFAULT_PRECISION = 6;
    /** The scale or number of digits to the right of the decimal separator. */
    int32_t scale;
    /** The value of the number without applying the scale. */
    int64_t value;

    DecimalBase(int32_t scale_,
                int64_t value_)
    : scale(std::move(scale_))
    , value(std::move(value_))
    {}

    virtual ~DecimalBase() = default;

protected:
    DecimalBase(const DecimalBase&) = default;
    DecimalBase(DecimalBase&&) = default;
    DecimalBase& operator=(const DecimalBase&) = default;
    DecimalBase& operator=(DecimalBase&&) = default;
};

}  // namespace verifone_sdk
