// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_payment.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class DeliveryMethod : int {
    /** Delivery method for printing the receipt on the default printer */
    PRINT,
    /** Delivery method for emailing the receipt to the customer */
    EMAIL,
    /** Delivery method for providing an SMS message to the customer, generally containing a link to an online receipt */
    SMS,
    /** The customer does not want a receipt */
    NONE,
};

constexpr std::string_view toString(const DeliveryMethod& arg) {
    switch(arg) {
        case DeliveryMethod::PRINT: return "PRINT";
        case DeliveryMethod::EMAIL: return "EMAIL";
        case DeliveryMethod::SMS: return "SMS";
        case DeliveryMethod::NONE: return "NONE";
        default: return "DeliveryMethod enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::DeliveryMethod> {
    size_t operator()(::verifone_sdk::DeliveryMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
