// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from psdk_internal.djinni

#pragma once

#include <cstdint>
#include <psdk/export.h>
#include <string>

namespace verifone_sdk {

struct PsdkDeviceInformation;

/** Receives the results when discovering devices using the Device Scanner. */
class PSDK_EXPORT DeviceScanListenerInterface {
public:
    virtual ~DeviceScanListenerInterface() {}

    /** The scan has started. */
    virtual void scanStarted() = 0;

    /** A device has been found. */
    virtual void deviceFound(const std::string & identifier, const PsdkDeviceInformation & device_information) = 0;

    /** A device that was found is no longer responding and should be removed from the list. */
    virtual void deviceLost(const std::string & identifier) = 0;

    /** The scan has ended. If the status code is non-zero, then the scan ended with an error. */
    virtual void scanEnded(int32_t status_code, const std::string & message) = 0;
};

}  // namespace verifone_sdk
