// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_payment.djinni

#pragma once

#include <memory>
#include <psdk/export.h>
#include <string>

namespace verifone_sdk {

enum class ContentType;

/** Display Output Interface */
class PSDK_EXPORT DisplayOutput {
public:
    virtual ~DisplayOutput() {}

    /**
     * Creates an instance of DisplayOutput
     * @param content The actual content to be presented.
     * @param contentType The type of content to be presented,
     *        {@link ContentType#HTML}, {@link ContentType#TEXT} or {@link ContentType#PREDEFINED}.
     */
    static std::shared_ptr<DisplayOutput> create(const std::string & content, ContentType contentType);
};

}  // namespace verifone_sdk
