// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CardInformation.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class EbtType : int {
    /** EBT benefits for food */
    FOOD_BENEFITS,
    /** EBT benefits for cash */
    CASH_BENEFITS,
    UNKNOWN,
    INVALID,
};

constexpr std::string_view toString(const EbtType& arg) {
    switch(arg) {
        case EbtType::FOOD_BENEFITS: return "FOOD_BENEFITS";
        case EbtType::CASH_BENEFITS: return "CASH_BENEFITS";
        case EbtType::UNKNOWN: return "UNKNOWN";
        case EbtType::INVALID: return "INVALID";
        default: return "EbtType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::EbtType> {
    size_t operator()(::verifone_sdk::EbtType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
