// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_entities.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace verifone_sdk {

/**
 * The Image class is an abstract class that provides the basis for handling
 * graphical images.
 */
class Image {
public:
    virtual ~Image() {}

    static std::shared_ptr<Image> create();

    /** Get raw encoded image data */
    virtual std::vector<uint8_t> getData() const = 0;

    /** Get image encoding format */
    virtual std::optional<std::string> getFormat() const = 0;

    /** Set raw encoded image data */
    virtual void setData(const std::vector<uint8_t> & image) = 0;

    /** Set image encoding format */
    virtual void setFormat(const std::optional<std::string> & format) = 0;
};

}  // namespace verifone_sdk
