// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_host_adapter.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class InstrumentType : int {
    /** Card Intrument Type */
    CARD,
    /** Pre Authorization Intrument Type */
    PRE_AUTHORIZATION,
    /** Token Intrument Type */
    TOKEN,
};

constexpr std::string_view toString(const InstrumentType& arg) {
    switch(arg) {
        case InstrumentType::CARD: return "CARD";
        case InstrumentType::PRE_AUTHORIZATION: return "PRE_AUTHORIZATION";
        case InstrumentType::TOKEN: return "TOKEN";
        default: return "InstrumentType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::InstrumentType> {
    size_t operator()(::verifone_sdk::InstrumentType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
