// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Installment.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class InstallmentType : int {
    /** Credit backed by the Merchant */
    MERCHANT_CREDIT,
    /** Credit backed by the cardholder */
    CARDHOLDER_CREDIT,
};

constexpr std::string_view toString(const InstallmentType& arg) {
    switch(arg) {
        case InstallmentType::MERCHANT_CREDIT: return "MERCHANT_CREDIT";
        case InstallmentType::CARDHOLDER_CREDIT: return "CARDHOLDER_CREDIT";
        default: return "InstallmentType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::InstallmentType> {
    size_t operator()(::verifone_sdk::InstallmentType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
