// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ItemType.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class ItemType : int {
    /** The action was performed with {@link Merchandise Merchandise}. */
    MERCHANDISE,
    /** The action was performed with {@link Modifier Modifiers}. */
    MODIFIER,
    /** The action was performed with {@link Offer Offers}. */
    OFFER,
    /** The action was performed with {@link Donation Donations}. */
    DONATION,
    /** The action was performed on all items. This is only relevant when purging. */
    ALL,
    /** Only used during error cases. */
    UNKNOWN,
};

constexpr std::string_view toString(const ItemType& arg) {
    switch(arg) {
        case ItemType::MERCHANDISE: return "MERCHANDISE";
        case ItemType::MODIFIER: return "MODIFIER";
        case ItemType::OFFER: return "OFFER";
        case ItemType::DONATION: return "DONATION";
        case ItemType::ALL: return "ALL";
        case ItemType::UNKNOWN: return "UNKNOWN";
        default: return "ItemType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::ItemType> {
    size_t operator()(::verifone_sdk::ItemType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
