/*
 * Copyright (c) 2021 by VeriFone, Inc.
 * All Rights Reserved.
 * THIS FILE CONTAINS PROPRIETARY AND CONFIDENTIAL INFORMATION
 * AND REMAINS THE UNPUBLISHED PROPERTY OF VERIFONE, INC.
 *
 * Use, disclosure, or reproduction is prohibited
 * without prior written approval from VeriFone, Inc.
 */

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated is to be modified by the localization script

#ifndef VERIFONE_SDK_LOCALIZED_STRINGS_H_
#define VERIFONE_SDK_LOCALIZED_STRINGS_H_

#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>

#include "LocalizedStringEnum.hpp"

namespace verifone_sdk {

struct LocalizedStrings {
  static std::optional<std::string_view> GetString(LocalizedStringEnum enum_key, const std::string& lang_key);
};

}  // namespace verifone_sdk

#endif  // VERIFONE_SDK_LOCALIZED_STRINGS_H_
