// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_payment.djinni

#pragma once

#include <memory>
#include <optional>
#include <string>

namespace verifone_sdk {

class CommerceListener;

/** Credentials used by loginWithCredentials. */
class LoginCredentials {
public:
    virtual ~LoginCredentials() {}

    /** Creates an instance of Credentials */
    static std::shared_ptr<LoginCredentials> create();

    static std::shared_ptr<LoginCredentials> createWith(const std::shared_ptr<CommerceListener> & listener, const std::optional<std::string> & userId, const std::optional<std::string> & password, const std::optional<std::string> & shiftNumber, const std::optional<std::string> & merchantId);

    /** Gets the Listener from the credentials */
    virtual std::shared_ptr<CommerceListener> getListener() const = 0;

    /** Sets the listener to the credentials */
    virtual void setListener(const std::shared_ptr<CommerceListener> & listener) = 0;

    /** Gets the the user id from the credentials */
    virtual std::optional<std::string> getUserId() const = 0;

    /** Sets the user id to the credentials */
    virtual void setUserId(const std::optional<std::string> & userId) = 0;

    /** Gets the the password from the credentials */
    virtual std::optional<std::string> getPassword() const = 0;

    /** Sets the password to the credentials */
    virtual void setPassword(const std::optional<std::string> & password) = 0;

    /** Gets the the shift number from the credentials */
    virtual std::optional<std::string> getShiftNumber() const = 0;

    /** Sets the shift number to the credentials */
    virtual void setShiftNumber(const std::optional<std::string> & shiftNumber) = 0;

    /** Gets the merchant id from the credentials */
    virtual std::optional<std::string> getMerchantId() const = 0;

    /** Sets the merchant id to the credentials */
    virtual void setMerchantId(const std::optional<std::string> & merchantId) = 0;
};

}  // namespace verifone_sdk
