// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VasCommands.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class NfcVasMode : int {
    /** Default. Once the VAS transaction is completed, NFC continues to get payment data from terminal */
    VAS_AND_PAYMENT,
    /** Behavior depends on VAS transaction response and NFC kernel in use */
    VAS_OR_PAYMENT,
    /** No VAS data transmitted */
    PAYMENT_ONLY,
    /** Only VAS data is transmitted */
    VAS_ONLY,
};

constexpr std::string_view toString(const NfcVasMode& arg) {
    switch(arg) {
        case NfcVasMode::VAS_AND_PAYMENT: return "VAS_AND_PAYMENT";
        case NfcVasMode::VAS_OR_PAYMENT: return "VAS_OR_PAYMENT";
        case NfcVasMode::PAYMENT_ONLY: return "PAYMENT_ONLY";
        case NfcVasMode::VAS_ONLY: return "VAS_ONLY";
        default: return "NfcVasMode enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::NfcVasMode> {
    size_t operator()(::verifone_sdk::NfcVasMode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
