// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Offer.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class OfferType : int {
    /** Merchant coupon offer type */
    MERCHANT_COUPON,
    /** Manufacturer coupon offer type */
    MANUFACTURER_COUPON,
    /**
     * A miscellaneous coupon offer type,
     * generally some kind of promotion by a third party
     */
    OTHER_COUPON,
    /**
     * Product discount offer type,
     * generally a product-specific sale or similar promotion
     */
    PRODUCT_DISCOUNT,
    /** Loyalty-related offer type */
    LOYALTY_CARD,
    /**
     * Transaction discount offer type,
     * This should not be tied to a specific item
     */
    TRANSACTION_DISCOUNT,
};

constexpr std::string_view toString(const OfferType& arg) {
    switch(arg) {
        case OfferType::MERCHANT_COUPON: return "MERCHANT_COUPON";
        case OfferType::MANUFACTURER_COUPON: return "MANUFACTURER_COUPON";
        case OfferType::OTHER_COUPON: return "OTHER_COUPON";
        case OfferType::PRODUCT_DISCOUNT: return "PRODUCT_DISCOUNT";
        case OfferType::LOYALTY_CARD: return "LOYALTY_CARD";
        case OfferType::TRANSACTION_DISCOUNT: return "TRANSACTION_DISCOUNT";
        default: return "OfferType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::OfferType> {
    size_t operator()(::verifone_sdk::OfferType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
