// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Offer.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class OfferStatus : int {
    SUCCESS,
    /** VAS data not found */
    VAS_DATA_NOT_FOUND,
    /** VAS data not activated */
    VAS_DATA_NOT_ACTIVATED,
    /** Wrong P1, P2 */
    WRONG_P1_P2,
    /** Wrong length of vas command data field */
    WRONG_LENGTH_VAS_COMMAND,
    /** User intervention required on mobile device */
    USER_INTERVENTION_REQUIRED_ON_TERMINAL,
    /** Incorrect data in the vas command field */
    INCORRECT_DATA_IN_VAS_COMMAND,
    /** Unsupported application version number */
    UNSUPPORTED_APPLICATION_VERSION_NUMBER,
};

constexpr std::string_view toString(const OfferStatus& arg) {
    switch(arg) {
        case OfferStatus::SUCCESS: return "SUCCESS";
        case OfferStatus::VAS_DATA_NOT_FOUND: return "VAS_DATA_NOT_FOUND";
        case OfferStatus::VAS_DATA_NOT_ACTIVATED: return "VAS_DATA_NOT_ACTIVATED";
        case OfferStatus::WRONG_P1_P2: return "WRONG_P1_P2";
        case OfferStatus::WRONG_LENGTH_VAS_COMMAND: return "WRONG_LENGTH_VAS_COMMAND";
        case OfferStatus::USER_INTERVENTION_REQUIRED_ON_TERMINAL: return "USER_INTERVENTION_REQUIRED_ON_TERMINAL";
        case OfferStatus::INCORRECT_DATA_IN_VAS_COMMAND: return "INCORRECT_DATA_IN_VAS_COMMAND";
        case OfferStatus::UNSUPPORTED_APPLICATION_VERSION_NUMBER: return "UNSUPPORTED_APPLICATION_VERSION_NUMBER";
        default: return "OfferStatus enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::OfferStatus> {
    size_t operator()(::verifone_sdk::OfferStatus type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
