// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_payment.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class PinRequestType : int {
    /** PinRequest to verify encrypted cardholder PIN */
    PIN_VERIFY,
    /** PinRequest to acquire encrypted cardholder PIN */
    PIN_ENTER,
    /** PinRequest to acquire and verify encrypted cardholder PIN */
    PIN_ENTER_AND_VERIFY,
};

constexpr std::string_view toString(const PinRequestType& arg) {
    switch(arg) {
        case PinRequestType::PIN_VERIFY: return "PIN_VERIFY";
        case PinRequestType::PIN_ENTER: return "PIN_ENTER";
        case PinRequestType::PIN_ENTER_AND_VERIFY: return "PIN_ENTER_AND_VERIFY";
        default: return "PinRequestType enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::PinRequestType> {
    size_t operator()(::verifone_sdk::PinRequestType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
