// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from psdk_internal.djinni

#pragma once

#include <optional>
#include <psdk/export.h>
#include <string>

namespace verifone_sdk {

enum class LocalizedStringEnum;

/** Contains those objects meant for internal usage only. Not to be exposed to third-parties. */
class PSDK_EXPORT PlatformContextInterface {
public:
    virtual ~PlatformContextInterface() {}

    /** Stores a value under the given key. */
    virtual void StoreValue(const std::string & key, const std::string & value) = 0;

    /** Returns true if the value is stored, or false if not. */
    virtual bool HasStoredValue(const std::string & key) = 0;

    /** Returns the value that was stored under the given key, or empty if not stored. */
    virtual std::optional<std::string> GetStoredValue(const std::string & key) = 0;

    /** Removes a key and its value */
    virtual void RemoveStoredValue(const std::string & key) = 0;

    /** Get the localized string based on the device language */
    virtual std::string GetLocalizedString(LocalizedStringEnum key) = 0;
};

}  // namespace verifone_sdk
