// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from PredefinedReferenceId.djinni

#pragma once

#include <psdk/export.h>
#include <string>
#include <utility>

namespace verifone_sdk {

/**
 * Use these constants to present text on the terminal when requesting input.
 * These prompts are localized by the terminal ahead of time, automatically
 * loading the correct localized version for the described prompt.
 */
struct PSDK_EXPORT PredefinedReferenceId final {

    /** Please Select Merchant */
    static std::string const POS_PROMPT_001;

    /** Please Select Currency */
    static std::string const POS_PROMPT_002;

    /** Please Select Language */
    static std::string const POS_PROMPT_003;

    /** Enter Authorization Code */
    static std::string const POS_PROMPT_004;

    /** Enter Cash Back */
    static std::string const POS_PROMPT_005;

    /** Enter Document Number */
    static std::string const POS_PROMPT_006;

    /** Enter Driver's License Number */
    static std::string const POS_PROMPT_007;

    /** Enter Government-issued ID */
    static std::string const POS_PROMPT_008;

    /** Enter Email */
    static std::string const POS_PROMPT_009;

    /** Enter ID */
    static std::string const POS_PROMPT_010;

    /** Enter Installment Number */
    static std::string const POS_PROMPT_011;

    /** Enter Invoice */
    static std::string const POS_PROMPT_012;

    /** Enter Loyalty ID */
    static std::string const POS_PROMPT_013;

    /** Enter Loyalty ID or Mobile Number */
    static std::string const POS_PROMPT_014;

    /** Enter Loyalty ID, Mobile Number, or swipe Loyalty Card */
    static std::string const POS_PROMPT_015;

    /** Enter Mileage */
    static std::string const POS_PROMPT_016;

    /** Enter Mobile Number */
    static std::string const POS_PROMPT_017;

    /** Enter New Value */
    static std::string const POS_PROMPT_018;

    /** Enter Order */
    static std::string const POS_PROMPT_019;

    /** Enter Password */
    static std::string const POS_PROMPT_020;

    /** Enter Previous Value */
    static std::string const POS_PROMPT_021;

    /** Enter Pump Number */
    static std::string const POS_PROMPT_022;

    /** Enter Tip Amount */
    static std::string const POS_PROMPT_023;

    /** Please Sign */
    static std::string const POS_PROMPT_024;

    /** Press Number for Manual */
    static std::string const POS_PROMPT_025;

    /** Are you sure? */
    static std::string const POS_PROMPT_026;

    /** Would you like to try again? */
    static std::string const POS_PROMPT_027;

    /** Try again? */
    static std::string const POS_PROMPT_028;

    /** Press Enter to Start */
    static std::string const POS_PROMPT_029;

    /** Press Enter to Retry */
    static std::string const POS_PROMPT_030;

    /** Press Enter to Bypass */
    static std::string const POS_PROMPT_031;

    /** Press Enter to Confirm */
    static std::string const POS_PROMPT_032;

    /** Cancel */
    static std::string const POS_PROMPT_033;

    /** Confirm */
    static std::string const POS_PROMPT_034;

    /** No */
    static std::string const POS_PROMPT_035;

    /** Reject */
    static std::string const POS_PROMPT_036;

    /** Yes */
    static std::string const POS_PROMPT_037;

    /** Further Action Required */
    static std::string const POS_PROMPT_038;

    /** Invalid Entry */
    static std::string const POS_PROMPT_039;

    /** Please contact support */
    static std::string const POS_PROMPT_040;

    /** Please retry */
    static std::string const POS_PROMPT_041;

    /** Please review the following and confirm */
    static std::string const POS_PROMPT_042;

    /** Please see phone */
    static std::string const POS_PROMPT_043;

    /** Please wait for assistance */
    static std::string const POS_PROMPT_044;

    /** Password Mismatch */
    static std::string const POS_PROMPT_045;

    /** Password Mismatch... Last Retry */
    static std::string const POS_PROMPT_046;

    /** Password Attempts Exceeded */
    static std::string const POS_PROMPT_047;

    /** Select ID */
    static std::string const POS_PROMPT_048;

    /** Select Invoice */
    static std::string const POS_PROMPT_049;

    /** Select Menu */
    static std::string const POS_PROMPT_050;

    /** Select one of the following options */
    static std::string const POS_PROMPT_051;

    /** Select Option */
    static std::string const POS_PROMPT_052;

    /** Select Order */
    static std::string const POS_PROMPT_053;

    /** Select Transaction */
    static std::string const POS_PROMPT_054;

    /** Select Table */
    static std::string const POS_PROMPT_055;

    /** Would you like a receipt? */
    static std::string const POS_PROMPT_056;

    /** How would you like your receipt? */
    static std::string const POS_PROMPT_057;

    /** Email */
    static std::string const POS_PROMPT_058;

    /** Print */
    static std::string const POS_PROMPT_059;

    /** SMS/Text */
    static std::string const POS_PROMPT_060;

    /** None */
    static std::string const POS_PROMPT_061;
};

}  // namespace verifone_sdk
