// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from psdk_elements.djinni

#pragma once

#include <psdk/export.h>
#include <string>
#include <utility>

namespace verifone_sdk {

/**
 * Various keys and values that can be used during initialization. 
 * Additional keys and values can be found in the PosInformation, 
 * PsdkDeviceInformation, and TransactionManager classes.
 */
struct PSDK_EXPORT PsdkInitializationConstants final {

    /**
     * Used during initialization to set the network configuration. The 
     * behavior defaults to NETWORK_CONFIGURATION_DYNAMIC_VALUE. 
     */
    static std::string const NETWORK_CONFIGURATION_KEY;

    /**
     * The network is configured to dynamic IP addresses, which means the 
     * library will scan the network to locate the device with the correct ID.
     */
    static std::string const NETWORK_CONFIGURATION_DYNAMIC_VALUE;

    /**
     * The network is configured with static IP addresses, which means this 
     * library will attempt to connect with the remembered IP address only,
     * and fail if it cannot connect to that IP address, instead of scanning the 
     * network for the device.
     */
    static std::string const NETWORK_CONFIGURATION_STATIC_VALUE;

    /**
     * The network is configured with service discovery, which means this
     * library will attempt to discover all the terminals in the local network.
     */
    static std::string const NETWORK_CONFIGURATION_SERVICE_DISCOVERY_VALUE;
};

}  // namespace verifone_sdk
