// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ReaderParameters.djinni

#pragma once

#include "PresentationMethod.hpp"
#include "TokenParameters.hpp"
#include <optional>
#include <psdk/export.h>
#include <string>
#include <utility>
#include <vector>

namespace verifone_sdk {

/** Card reader configuration parameters */
struct PSDK_EXPORT ReaderParameters final {
    /** An optional message to display to the customer unless isBackground is true. */
    std::optional<std::string> message;
    /** Optionally restrict the readers to a list of presentation methods. */
    std::optional<std::vector<PresentationMethod>> presentationMethodNames;
    /** Optionally restricts the readers to a set of AIDs. */
    std::optional<std::vector<std::string>> aidList;
    /**
     * Set to true if the tap/swipe/insert dialogue should be suppressed on the 
     * terminal screen. Defaults to false. This will be quietly ignored for those 
     * terminals which do not support this configuration.
     */
    bool isBackground;
    /**
     * Optionally request a token or multiple tokens to be generated according
     * to the provided parameters.
     */
    std::optional<std::vector<TokenParameters>> tokenParameters;

    ReaderParameters(std::optional<std::string> message_,
                     std::optional<std::vector<PresentationMethod>> presentationMethodNames_,
                     std::optional<std::vector<std::string>> aidList_,
                     bool isBackground_,
                     std::optional<std::vector<TokenParameters>> tokenParameters_)
    : message(std::move(message_))
    , presentationMethodNames(std::move(presentationMethodNames_))
    , aidList(std::move(aidList_))
    , isBackground(std::move(isBackground_))
    , tokenParameters(std::move(tokenParameters_))
    {}
};

}  // namespace verifone_sdk
