// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_payment_reports.djinni

#pragma once

#include "Decimal.hpp"
#include <cstdint>
#include <optional>
#include <psdk/export.h>
#include <string>
#include <utility>

namespace verifone_sdk {

/** Represents the consolidated totals of sales/refunds/cashbacks/surcharges/gratuities */
struct PSDK_EXPORT ReconciliationSummary final {
    /** Total transaction count. */
    std::optional<int32_t> totalTransactionCount;
    /** Total Net amount of whole transactions */
    std::optional<Decimal> totalNetAmount;
    /** Total refunds count. */
    std::optional<int32_t> totalRefundsCount;
    /** Total refunds amount. */
    std::optional<Decimal> totalRefundsAmount;
    /** Total sales count. */
    std::optional<int32_t> totalSalesCount;
    /** Total Sales amount. */
    std::optional<Decimal> totalSalesAmount;
    /** Total Cashbacks count. */
    std::optional<int32_t> totalCashbacksCount;
    /** Total Cashbacks amount. */
    std::optional<Decimal> totalCashbacksAmount;
    /** Total Surcharges count. */
    std::optional<int32_t> totalSurchargesCount;
    /** Total Surcharges amount. */
    std::optional<Decimal> totalSurchargesAmount;
    /** Total Gratuities count. */
    std::optional<int32_t> totalGratuitiesCount;
    /** Total Gratuities amount. */
    std::optional<Decimal> totalGratuitiesAmount;
    /** The acquirer name. */
    std::optional<std::string> acquirerName;

    ReconciliationSummary(std::optional<int32_t> totalTransactionCount_,
                          std::optional<Decimal> totalNetAmount_,
                          std::optional<int32_t> totalRefundsCount_,
                          std::optional<Decimal> totalRefundsAmount_,
                          std::optional<int32_t> totalSalesCount_,
                          std::optional<Decimal> totalSalesAmount_,
                          std::optional<int32_t> totalCashbacksCount_,
                          std::optional<Decimal> totalCashbacksAmount_,
                          std::optional<int32_t> totalSurchargesCount_,
                          std::optional<Decimal> totalSurchargesAmount_,
                          std::optional<int32_t> totalGratuitiesCount_,
                          std::optional<Decimal> totalGratuitiesAmount_,
                          std::optional<std::string> acquirerName_)
    : totalTransactionCount(std::move(totalTransactionCount_))
    , totalNetAmount(std::move(totalNetAmount_))
    , totalRefundsCount(std::move(totalRefundsCount_))
    , totalRefundsAmount(std::move(totalRefundsAmount_))
    , totalSalesCount(std::move(totalSalesCount_))
    , totalSalesAmount(std::move(totalSalesAmount_))
    , totalCashbacksCount(std::move(totalCashbacksCount_))
    , totalCashbacksAmount(std::move(totalCashbacksAmount_))
    , totalSurchargesCount(std::move(totalSurchargesCount_))
    , totalSurchargesAmount(std::move(totalSurchargesAmount_))
    , totalGratuitiesCount(std::move(totalGratuitiesCount_))
    , totalGratuitiesAmount(std::move(totalGratuitiesAmount_))
    , acquirerName(std::move(acquirerName_))
    {}
};

}  // namespace verifone_sdk
