// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from peripherals.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class ScannerBarcodeFormatEnum : int {
    /** NONE barcode format. */
    NONE,
    /** Partial format. */
    PARTIAL,
    /** EAN8 format. */
    EAN8,
    /** UPCE format. */
    UPCE,
    /** ISBN10 format. */
    ISBN10,
    /** UPCA format. */
    UPCA,
    /** EAN-13 format. */
    EAN13,
    /** IISBN13 format. */
    ISBN13,
    /** I25 format. */
    I25,
    /** DATABAR format. */
    DATABAR,
    /** DATABAR_EXP format. */
    DATABAR_EXP,
    /** CODABAR */
    CODABAR,
    /** CODE39 */
    CODE39,
    /** PDF417 format. */
    PDF417,
    /** QRCODE format. */
    QRCODE,
    /** CODE93 format. */
    CODE93,
    /** CODE128 format. */
    CODE128,
    /** Aztec format. */
    AZTEC,
    /** Data Matrix format. */
    DATA_MATRIX,
    /** Maxicode format. */
    MAXICODE,
    /** GS1-128 format. Formerly known as EAN-128 */
    GS1_128,
    /** CODE11 format. */
    CODE11,
    /** CODE32 format. */
    CODE32,
    /** MSI format. */
    MSI,
    /** Chinese 2 of 5 (Chinese Post) format. */
    CHINESE_POST,
    /** Korean 3 of 5 (Korean Post) format. */
    KOREAN_POST,
    /** MICRO QRCODE format. */
    UQRCODE,
};

constexpr std::string_view toString(const ScannerBarcodeFormatEnum& arg) {
    switch(arg) {
        case ScannerBarcodeFormatEnum::NONE: return "NONE";
        case ScannerBarcodeFormatEnum::PARTIAL: return "PARTIAL";
        case ScannerBarcodeFormatEnum::EAN8: return "EAN8";
        case ScannerBarcodeFormatEnum::UPCE: return "UPCE";
        case ScannerBarcodeFormatEnum::ISBN10: return "ISBN10";
        case ScannerBarcodeFormatEnum::UPCA: return "UPCA";
        case ScannerBarcodeFormatEnum::EAN13: return "EAN13";
        case ScannerBarcodeFormatEnum::ISBN13: return "ISBN13";
        case ScannerBarcodeFormatEnum::I25: return "I25";
        case ScannerBarcodeFormatEnum::DATABAR: return "DATABAR";
        case ScannerBarcodeFormatEnum::DATABAR_EXP: return "DATABAR_EXP";
        case ScannerBarcodeFormatEnum::CODABAR: return "CODABAR";
        case ScannerBarcodeFormatEnum::CODE39: return "CODE39";
        case ScannerBarcodeFormatEnum::PDF417: return "PDF417";
        case ScannerBarcodeFormatEnum::QRCODE: return "QRCODE";
        case ScannerBarcodeFormatEnum::CODE93: return "CODE93";
        case ScannerBarcodeFormatEnum::CODE128: return "CODE128";
        case ScannerBarcodeFormatEnum::AZTEC: return "AZTEC";
        case ScannerBarcodeFormatEnum::DATA_MATRIX: return "DATA_MATRIX";
        case ScannerBarcodeFormatEnum::MAXICODE: return "MAXICODE";
        case ScannerBarcodeFormatEnum::GS1_128: return "GS1_128";
        case ScannerBarcodeFormatEnum::CODE11: return "CODE11";
        case ScannerBarcodeFormatEnum::CODE32: return "CODE32";
        case ScannerBarcodeFormatEnum::MSI: return "MSI";
        case ScannerBarcodeFormatEnum::CHINESE_POST: return "CHINESE_POST";
        case ScannerBarcodeFormatEnum::KOREAN_POST: return "KOREAN_POST";
        case ScannerBarcodeFormatEnum::UQRCODE: return "UQRCODE";
        default: return "ScannerBarcodeFormatEnum enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::ScannerBarcodeFormatEnum> {
    size_t operator()(::verifone_sdk::ScannerBarcodeFormatEnum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
