// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from SdiManager.djinni

#pragma once

#include <memory>

namespace verifone_sdk {

class SdiTlv;

/** Notify callback interface. */
class SdiNotifyCallback {
public:
    virtual ~SdiNotifyCallback() {}

    /**
     * param t TLV data received from SDI server
     * note Important: The callback function must not invoke any method of the
     * same SDIClient object or a deadlock may occur.
     */
    virtual void callback(const std::shared_ptr<SdiTlv> & tlvData) = 0;
};

}  // namespace verifone_sdk
