// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from SdiManager.djinni

#pragma once

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace verifone_sdk {

/**
 * Sdi Manager
 * Return data for {@link SdiManager#receivedMessage}.
 */
struct SdiReceivedMessage final {
    /** 0 in case of success, -1 in case of failure */
    int32_t result;
    /** sw1sw2 SW1 SW2 packed into a int 32 as returned from SDI */
    int32_t sw1sw2;
    /** message data */
    std::optional<std::vector<uint8_t>> data;

    SdiReceivedMessage(int32_t result_,
                       int32_t sw1sw2_,
                       std::optional<std::vector<uint8_t>> data_)
    : result(std::move(result_))
    , sw1sw2(std::move(sw1sw2_))
    , data(std::move(data_))
    {}
};

}  // namespace verifone_sdk
