// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Tokens.djinni

#pragma once

#include "TokenCreationMethod.hpp"
#include "TokenType.hpp"
#include <psdk/export.h>
#include <string>
#include <utility>

namespace verifone_sdk {

/** Parameters required to create a token. */
struct PSDK_EXPORT TokenParameters final {
    /** Method to create the token. */
    TokenCreationMethod creationMethod;
    /** Scope of the token parameter. */
    std::string scope;
    /** Type of the token. */
    TokenType tokenType;

    TokenParameters(TokenCreationMethod creationMethod_,
                    std::string scope_,
                    TokenType tokenType_)
    : creationMethod(std::move(creationMethod_))
    , scope(std::move(scope_))
    , tokenType(std::move(tokenType_))
    {}
};

}  // namespace verifone_sdk
