// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_entities.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class TokenizationMethod : int {
    /** PAN token */
    PANTOKEN,
    /** Fast token */
    FASTTOKEN,
    /** Custom */
    CUSTOM,
    /** Default */
    DEFAULT,
    /** None */
    NONE,
    /** The count of all currently available enum values */
    MAX_COUNT,
};

constexpr std::string_view toString(const TokenizationMethod& arg) {
    switch(arg) {
        case TokenizationMethod::PANTOKEN: return "PANTOKEN";
        case TokenizationMethod::FASTTOKEN: return "FASTTOKEN";
        case TokenizationMethod::CUSTOM: return "CUSTOM";
        case TokenizationMethod::DEFAULT: return "DEFAULT";
        case TokenizationMethod::NONE: return "NONE";
        case TokenizationMethod::MAX_COUNT: return "MAX_COUNT";
        default: return "TokenizationMethod enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::TokenizationMethod> {
    size_t operator()(::verifone_sdk::TokenizationMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
