// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Tokens.djinni

#pragma once

#include <functional>
#include <string>

namespace verifone_sdk {

enum class TokenCreationMethod : int {
    /** Create if not existing. */
    CREATE_OR_RETRIEVE,
    /** Create or replace existing. */
    CREATE_OR_REPLACE,
    /** Retrieve existing. */
    RETRIEVE_ONLY,
};

constexpr std::string_view toString(const TokenCreationMethod& arg) {
    switch(arg) {
        case TokenCreationMethod::CREATE_OR_RETRIEVE: return "CREATE_OR_RETRIEVE";
        case TokenCreationMethod::CREATE_OR_REPLACE: return "CREATE_OR_REPLACE";
        case TokenCreationMethod::RETRIEVE_ONLY: return "RETRIEVE_ONLY";
        default: return "TokenCreationMethod enum value not supported";
    }
}

}  // namespace verifone_sdk

namespace std {

template <>
struct hash<::verifone_sdk::TokenCreationMethod> {
    size_t operator()(::verifone_sdk::TokenCreationMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
