// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_payment.djinni

#pragma once

#include <memory>
#include <optional>
#include <psdk/export.h>
#include <string>

namespace verifone_sdk {

class CommerceResponse;
class Transaction;

class PSDK_EXPORT TransactionEventResponse {
public:
    virtual ~TransactionEventResponse() {}

    /** Generate CommerceResponse from the provided response */
    static std::shared_ptr<CommerceResponse> asCommerceResponse(const std::shared_ptr<TransactionEventResponse> & transactionEventResponse);

    /** Return invoice id from response */
    virtual std::optional<std::string> getInvoiceId() const = 0;

    /** Return transaction from response */
    virtual std::shared_ptr<Transaction> getTransaction() const = 0;

    /** Update transaction from response */
    virtual void updateTransaction(const std::shared_ptr<Transaction> & transaction) = 0;
};

}  // namespace verifone_sdk
