// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from TypeValue.djinni

#pragma once

#include <optional>
#include <psdk/export.h>
#include <string>
#include <utility>

namespace verifone_sdk {

/** TypeValue */
struct PSDK_EXPORT TypeValue final {
    /**
     * @param Type optional. Indicating type of function for customer data
     * Example: "DU" is a dynamic URL function.
     */
    std::optional<std::string> type;
    /** @param pushDataValue optional. Actual customer data. */
    std::optional<std::string> value;

    TypeValue(std::optional<std::string> type_,
              std::optional<std::string> value_)
    : type(std::move(type_))
    , value(std::move(value_))
    {}
};

}  // namespace verifone_sdk
