// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_verifone_commerce_entities.djinni

#pragma once

#include <optional>
#include <string>
#include <utility>

namespace verifone_sdk {

struct Venue final {
    /** record id */
    std::optional<std::string> recordId;
    /** The name for the venue as set by the merchant. If not set, this returns null. */
    std::optional<std::string> venueName;
    /**
     * The address of the venue as a single string, following appropriate regional formatting.
     * This string may contain linebreaks and other formatting characters, and is suitable for printing on the receipt. If not set, this returns null.
     */
    std::optional<std::string> venueAddress;

    Venue(std::optional<std::string> recordId_,
          std::optional<std::string> venueName_,
          std::optional<std::string> venueAddress_)
    : recordId(std::move(recordId_))
    , venueName(std::move(venueName_))
    , venueAddress(std::move(venueAddress_))
    {}
};

}  // namespace verifone_sdk
